spring.application.name=backend

#server configuratation
server.port=8080

#Database configuration (H2 for development, will reset as restart)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

#PostgreSQL configuration (for data inspection now)
#spring.datasource.url=jdbc:postgresql://localhost:5432/mygame
#spring.datasource.username=meixiaobin
#spring.datasource.password=
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


##JPA Configuration
#Tells hibernate to use H2 SQL dialct
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#Create table at start and delete at shutdown
spring.jpa.hibernate.ddl-auto=create-drop
#print sql on this console
spring.jpa.show-sql=true
#format sql output
spring.jpa.properties.hibernate.format_sql=true

## H2 console (for developlment)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

##CORS
#Allow request from frontend (else browser will block API calls
cors.allowed-origins=http://localhost:5173

#Logging (debug
logging.level.com.mygame.backend=DEBUG
